import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header"; // Điều chỉnh đường dẫn nếu cần
import Footer from "../components/layout/Footer"; // Điều chỉnh đường dẫn nếu cần
import I18nProvider from "@/components/providers/I18nProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
        <Header />
        {children} {/* Nội dung từ page.tsx */}
        <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}